import crypto from 'crypto'
import esbuild from 'esbuild'
import fs from 'fs/promises'
import path from 'path'
import { JSDOM } from 'jsdom'
import lodashTemplate from 'lodash/template'

export interface Configuration {
    files: HtmlFileConfiguration[],
}

export interface HtmlFileConfiguration {
    /** Output filename, eg. index.html (relative to the output directory) */
    filename: string,
    /** Entry points to inject into the HTML, eg. ['src/index.jsx'].
     * Default to `esbuildOptions.entryPoints` */
    entryPoints?: string[],
    /** Optional title to inject into head */
    title?: string,
    /** HTML template string. Defaults to a blank template, unless `htmlFile` is set */
    htmlTemplate?: string,
    /** Read the template from an HTML file on disk instead of `htmlTemplate` */
    htmlFile?: string,
    /** A map of custom variable definitions for lodash */
    define?: Record<string, string>,
    /** How to load injected script tags. Defaults to defer */
    scriptLoading?: 'blocking' | 'defer' | 'module',
    /** Optional favicon to inject into head */
    favicon?: string,
    /** Whether to find related output CSS files and inject them into the HTML.
     * Defaults to true */
    findRelatedCssFiles?: boolean,
    /** Ignore specific assets, in case they will be injected or generated by other means.
     * If set to `true`, ignores all assets. */
    ignoreAssets?: boolean | string[],
    /** Inline content of JS files, CSS files, or both */
    inline?: boolean | {
        css?: boolean
        js?: boolean
    } | ((filepath: string) => boolean),
    /** Extra script tags to include in the HTML file */
    extraScripts?: (string | {
        src: string,
        attrs?: { [key: string]: string }
    })[],
    /** Extra HTML to append to the document head */
    appendHead?: string,
    /** Extra HTML to prepend to the document body */
    prependBody?: string,
    /** Extra HTML to append to the document body */
    appendBody?: string,
    hash?: boolean | string,
}

type AssetList = {[k: string]: {dest: string; htmlFile: string}}
type InternalElement = Element & {_int?: boolean}

//Type polyfill for RegExp.escape
declare global {
    interface RegExpConstructor {
        escape(s: string): string;
    }
}

const defaultHtmlTemplate =
`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
  </head>
  <body>
  </body>
</html>`

// This function joins a path, and in case of windows, it converts backward slashes ('\') forward slashes ('/').
function posixJoin(...paths: string[]): string {
    const joined = path.join(...paths)
    if (path.sep === '/') {
        return joined
    }
    return joined.split(path.sep).join(path.posix.sep)
}

function appendHtmlStr(el: HTMLElement, html: string, pre = false) {
    const doc = new JSDOM(html).window.document
    el[pre ? 'prepend': 'append'](...doc.head.children, ...doc.body.children)
}

const pathsToRegex = (paths?: boolean | string[]) => Array.isArray(paths) ? paths.map(p => new RegExp(`^${RegExp.escape(path.resolve(p)).replace(/\\\\\\\*\\\*\\\\/g, '\\\\.+').replace(/\\\*/g, '[^\\\\]+')}$`)) : undefined

type Outputs = (esbuild.Metafile['outputs'][0] & {dest: string, absSrc?: string})[]

export const htmlPlugin = (configuration: Configuration = { files: [], }): esbuild.Plugin => {
    let logInfo = false

    function collectEntrypoints(build: esbuild.PluginBuild, config: HtmlFileConfiguration, outputs: Outputs, ignoreAssets?: RegExp[]) {
        const initEntryPts = (config.entryPoints ?? build.initialOptions.entryPoints as string[]).filter(ep => {
            if(ignoreAssets) {
                ep = path.resolve(ep)
                if(ignoreAssets.find(r => r.test(ep!))) return
            }
            return true
        }).map(ep => ep.replace(/\\/g, '/')) as (string | false)[]
        const entryRegex = pathsToRegex(initEntryPts as string[])!

        const entryPoints = outputs.filter(out => out.absSrc && entryRegex.find((r, i) => {
            if(r.test(out.absSrc!)) {
                initEntryPts[i] = false
                return true
            }
        }))

        for (const entry of initEntryPts) if (entry !== false)
            console.log(`⚠️ for "${config.filename}", entrypoint "${entry}" was requested, but not found.`)

        return entryPoints
    }

    async function renderTemplate({ htmlTemplate, htmlFile, define }: HtmlFileConfiguration) {
        const template = htmlFile
            ? await fs.readFile(htmlFile, {encoding: 'utf8'})
            : htmlTemplate || defaultHtmlTemplate

        const compiledTemplateFn = lodashTemplate(template, { interpolate: /<%=([\s\S]+?)%>/g })
        return compiledTemplateFn({ define })
    }

    // use the same joinWithPublicPath function as esbuild:
    //  https://github.com/evanw/esbuild/blob/a1ff9d144cdb8d50ea2fa79a1d11f43d5bd5e2d8/internal/bundler/bundler.go#L533
    function joinWithPublicPath(publicPath: string, relPath: string) {
        relPath = path.normalize(relPath)

        if (!publicPath) {
            publicPath = '.'
        }

        let slash = '/'
        if (publicPath.endsWith('/')) {
            slash = ''
        }
        return `${publicPath}${slash}${relPath}`
    }

    async function injectFiles(dom: JSDOM, assets: { dest: string }[], outDir: string, publicPath: string | undefined, config: HtmlFileConfiguration, outputs: Outputs, foundAssets: AssetList, ignoreAssets?: RegExp[]) {
        const document = dom.window.document
        if(config.appendBody) appendHtmlStr(document.body, config.appendBody)
        for (const script of config?.extraScripts || []) {
            const scriptTag = document.createElement('script')
            if (typeof script === 'string') {
                scriptTag.setAttribute('src', script)
            } else {
                scriptTag.setAttribute('src', script.src)
                Object.entries(script.attrs || {}).forEach(([key, value]) => {
                    scriptTag.setAttribute(key, value)
                })
            }
            document.body.append(scriptTag)
        }

        for (const out of assets) {
            let targetPath: string
            if (publicPath) {
                targetPath = joinWithPublicPath(publicPath, path.relative(outDir, out.dest))
            } else {
                const htmlFileDirectory = posixJoin(outDir, config.filename)
                targetPath = path.relative(path.dirname(htmlFileDirectory), out.dest)
            }
            if (config.hash) {
                const hashableContents = config.hash === true ? `${Date.now()}` : config.hash
                targetPath = `${targetPath}?${crypto.createHash('md5').update(hashableContents).digest('hex')}`
            }
            const ext = path.parse(out.dest).ext

            // Inline the JavaScript and CSS files if the option is set.
            const { inline } = config

            const isInline = () => {
                if (!inline) return false
                const extension = ext.replace('.', '') as 'css' | 'js'
                return (
                    (typeof inline === 'boolean' && inline === true) ||
                    (typeof inline === 'object' && inline[extension] === true) ||
                    (typeof inline === 'function' && inline(out.dest))
                )
            }

            if (ext === '.js') {
                const scriptTag = document.createElement('script')

                // Check if the JavaScript should be inlined.
                if (isInline()) {
                    if (logInfo) console.log('Inlining script', out.dest)
                    // Read the content of the JavaScript file, then append to the script tag
                    scriptTag.textContent = await fs.readFile(out.dest, 'utf-8')
                } else {
                    // If not inlined, set the 'src' attribute as usual.
                    scriptTag.setAttribute('src', targetPath)
                }

                if (config.scriptLoading === 'module') {
                    // If module, add type="module"
                    scriptTag.setAttribute('type', 'module')
                } else if (!isInline() && (!config.scriptLoading || config.scriptLoading === 'defer')) {
                    // if scriptLoading is unset or defer, use defer
                    scriptTag.setAttribute('defer', '')
                }

                document.body.append(scriptTag)
            } else if (ext === '.css') {
                // Check if the CSS should be inlined -> if so, use style tags instead of link tags.
                if (isInline()) {
                    const styleTag = document.createElement('style')
                    const styleContent = await fs.readFile(out.dest, 'utf-8')
                    styleTag.textContent = styleContent
                    document.head.append(styleTag)
                    continue // no need to set any attributes
                }

                const linkTag = document.createElement('link');
                (linkTag as InternalElement)._int = true
                linkTag.setAttribute('rel', 'stylesheet')
                linkTag.setAttribute('href', targetPath)
                document.head.appendChild(linkTag)
            } else if (logInfo) {
                console.log(`Warning: found file ${targetPath}, but it was neither .js nor .css`)
            }
        }
        if(config.appendHead) appendHtmlStr(document.head, config.appendHead)
        if(config.prependBody) appendHtmlStr(document.body, config.prependBody, true)

        const htmlAtRoot = posixJoin(config.filename).indexOf(path.sep) === -1

        //Find & replace all source links
        if(config.ignoreAssets === true) return
        for(const el of document.querySelectorAll('img,object,link')) {
            if((el as InternalElement)._int) continue

            let srcProp = 'src'
            switch(el.tagName) {
            case 'OBJECT': srcProp = 'data'; break
            case 'LINK': srcProp = 'href'
            }
            let src = el.getAttribute(srcProp)
            if(!src || src.indexOf('://') !== -1) continue //Absolute URI
            if(src.startsWith('/')) src = src.slice(1) //Relative to working dir
            else src = path.join(config.htmlFile ? //Relative to file dir
                path.dirname(config.htmlFile) : '', src)

            let name = path.basename(src)
            const dest = posixJoin(path.dirname(path.join(outDir, config.filename)), name)
            src = path.resolve(src)
            if(ignoreAssets) {
                let ignore = false
                for(const r of ignoreAssets) if(r.test(src)) ignore = true
                if(ignore) continue //Ignored
            }

            const out = outputs.find(o => o.absSrc === src)
            if(out) { //Already in build output
                name = path.relative(outDir, out.dest)
            } else { //New asset
                foundAssets[src] = {dest, htmlFile: config.filename}
            }

            if(!htmlAtRoot) name = publicPath ? joinWithPublicPath(publicPath, name) : '/' + name
            el.setAttribute(srcProp, name)
        }
    }

    return {
        name: 'esbuild-html-plugin',
        setup(build) {
            if (build.initialOptions.metafile === false) {
                throw new Error('metafile is explicitly disabled. esbuild-html-plugin needs this to be enabled.')
            }
            // we need the metafile. If it's not set, we can set it to `true`
            build.initialOptions.metafile = true
            if (!build.initialOptions.outdir) {
                throw new Error('outdir must be set')
            }

            //Add HTML files to watch list
            let watched = false
            build.onLoad({filter: /./}, () => {
                if(!watched) {
                    watched = true
                    const watchFiles = []
                    for(const f of configuration.files) if(f.htmlFile)
                        watchFiles.push(path.resolve(f.htmlFile))
                    return {watchFiles}
                }
            })

            build.onEnd(async result => {
                const startTime = Date.now()
                watched = false

                if (build.initialOptions.logLevel == 'debug' || build.initialOptions.logLevel == 'info') {
                    logInfo = true
                }
                if (logInfo) console.log()

                // Note: we can safely disable this rule here, as we already asserted this in setup.onStart
                const outdir = build.initialOptions.outdir!
                const publicPath = build.initialOptions.publicPath
                const foundAssets: AssetList = {}

                //Flatten outputs into array w/ path and absolute entryPoint
                if (!result.metafile?.outputs) throw new Error('Metafile outputs missing!')
                const outputs: Outputs = Object.entries(result.metafile.outputs).map(([dest, out]) => {
                    const src = out.entryPoint || Object.keys(out.inputs)[0]
                    return { dest, absSrc: src && path.resolve(src), ...out}
                })

                for (const config of configuration.files) {
                    const ignoreAssets = pathsToRegex(config.ignoreAssets)
                    const entrypoints = collectEntrypoints(build, config, outputs, ignoreAssets)

                    // All output files relevant for this html file
                    const outputFiles: { dest: string }[] = []
                    for (const ep of entrypoints) {
                        outputFiles.push(ep)
                        if (config.findRelatedCssFiles !== false && ep.cssBundle)
                            outputFiles.push({ dest: ep.cssBundle })
                    }

                    const templatingResult = await renderTemplate(config)

                    // Next, we insert the found files into the htmlTemplate - if no htmlTemplate was specified, we default to a basic one.
                    const dom = new JSDOM(templatingResult)
                    const document = dom.window.document

                    if (config.title) {
                        // If a title was given, we pass the title as well
                        document.title = config.title
                    }

                    if (config.favicon) {
                        // Injects a favicon if present
                        const iconName = 'favicon' + path.extname(config.favicon)
                        try {
                            await fs.copyFile(config.favicon, `${outdir}/${iconName}`)
                        } catch(e) {
                            if ((e as {code: string}).code === 'ENOENT')
                                throw new Error(`favicon "${config.favicon}" does not exist`)
                            throw e
                        }

                        const linkTag = document.createElement('link');
                        (linkTag as InternalElement)._int = true
                        linkTag.setAttribute('rel', 'icon')

                        let iconPublicPath = `/${iconName}`
                        if (publicPath) iconPublicPath = joinWithPublicPath(publicPath, iconPublicPath)
                        linkTag.setAttribute('href', iconPublicPath)
                        document.head.appendChild(linkTag)
                    }

                    await injectFiles(dom, outputFiles, outdir, publicPath, config, outputs, foundAssets, ignoreAssets)

                    const out = posixJoin(outdir, config.filename)
                    await fs.mkdir(path.dirname(out), {
                        recursive: true,
                    })
                    await fs.writeFile(out, dom.serialize())
                    const stat = await fs.stat(out)
                    if (logInfo) console.log(`  ${out} - ${stat.size}`)
                }

                //Write assets
                for(const src in foundAssets) {
                    const asset = foundAssets[src]
                    try {
                        await fs.copyFile(src, asset.dest)
                    } catch(e) {
                        throw new Error(`Could not include asset ${src} required by ${asset.htmlFile}`, {cause: e})
                    }
                }

                if (logInfo) console.log(`HTML Plugin Done in ${Date.now() - startTime}ms`)
            })
        }
    }
}
